minimal_mistakes_skin    : "default"  # 전체적인 블로그의 색감을 정하는 값입니다.
                           # "default" "air", "aqua", "contrast", "dark"
                           # "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "ko-KR" 
title                    : "이승현의 포트폴리오"
title_separator          : "-"
subtitle                 : ""  
name                     : "이승현"
description              : "포트폴리오" 
url                      : "https://LeeSeungHyun9661.github.io"
baseurl                  : 
repository               : "https://github.com/LeeSeungHyun9661/LeeSeungHyun9661.github.io.git"
teaser                   :
logo                     : 
masthead_title           : "안녕하세요!" .