# Site Settings
locale                   : "ko-KR" 
title                    : "seunghyeon lee's profile"
title_separator          : "-"
subtitle                 : ""  
name                     : "seunghyeon lee"
description              : "" 
url                      : "https://seunghyeonlee9661.github.io"
baseurl                  : 
repository               : "https://github.com/seunghyeonlee9661/seunghyeonlee9661.github.io.git"
teaser                   :
logo                     : 
masthead_title           : "This is seunghyeon's Programmer Profile"
